
skillMetadata:
  sections:
    - name: Pairing new devices << Name of section
      fields:
        - name: trust_new_devices
          type: checkbox
          label: Automatically trust new paired devices?
          value: "false"
        - name: deactivate_bluetooth
          type: checkbox
          label: Deactivate bluetooth when skill is stopped?
          value: "false"
